spring.application.name=tc
#conexion a MySql

# Muestra el error exacto en consola
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG

spring.datasource.url = jdbc:mysql://localhost:3307/recursos_humanos_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto= update 
spring.jpa.show-sql=true


